import { ArrowUpRight, TrendingUp, MoreHorizontal, Calendar, Activity, Zap } from 'lucide-react';
import { SalesChart } from '@/components/dashboard/SalesChart';
import { getUserSubscription } from '@/app/actions/user';

export default async function Dashboard() {
    const subscriptionPlan = await getUserSubscription();

    return (
        <div className="grid grid-cols-1 xl:grid-cols-12 gap-8 pb-10">

            {/* Widget Kiri (Card): Trending Prediction */}
            <div className="xl:col-span-4 flex flex-col gap-6">
                <div className="bg-white rounded-[2rem] p-8 shadow-sm border border-gray-100/50 h-full relative overflow-hidden group hover:shadow-xl hover:shadow-indigo-50/50 transition-all duration-500">
                    {/* Background decoration */}
                    <div className="absolute top-[-20%] right-[-20%] w-64 h-64 bg-indigo-50/50 rounded-full blur-3xl opacity-60 group-hover:opacity-100 transition-opacity"></div>

                    <div className="relative z-10 flex flex-col h-full">
                        <div className="flex items-center justify-between mb-6">
                            <div className="flex items-center gap-2 px-3 py-1 bg-indigo-50 rounded-full w-fit">
                                <Zap className="w-3 h-3 text-indigo-600 fill-current" />
                                <span className="text-xs font-bold text-indigo-700 uppercase tracking-wider">AI Forecast</span>
                            </div>
                            <button className="text-gray-400 hover:text-gray-600"><MoreHorizontal className="w-5 h-5" /></button>
                        </div>

                        <h3 className="text-2xl font-bold text-gray-800 mb-1 leading-tight">Trending <br />Prediction</h3>
                        <p className="text-sm text-gray-400 mb-8">Generated by AI Engine</p>

                        <div className="flex items-center gap-3 mb-8">
                            <span className="text-5xl font-black text-gray-900 tracking-tighter">+24.5%</span>
                            <span className="px-2 py-1 bg-green-100/50 text-green-600 text-xs font-bold rounded-lg flex items-center">
                                <ArrowUpRight className="w-3 h-3 mr-1" /> MoM
                            </span>
                        </div>

                        {/* Product Mock */}
                        <div className="mt-auto bg-gradient-to-br from-white to-gray-50 rounded-2xl p-4 border border-gray-100 flex items-center gap-4 shadow-sm group-hover:scale-[1.02] transition-transform duration-300">
                            <div className="w-16 h-16 bg-white rounded-xl shadow-md flex items-center justify-center text-3xl shrink-0">👟</div>
                            <div>
                                <h4 className="font-bold text-gray-800">Summer Sneakers</h4>
                                <p className="text-xs text-indigo-500 font-semibold mt-1">Expected High Demand</p>
                            </div>
                            <div className="ml-auto">
                                <div className="w-10 h-10 rounded-full bg-indigo-600 flex items-center justify-center text-white shadow-lg shadow-indigo-200">
                                    <ArrowUpRight className="w-5 h-5" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {/* Widget Utama (Besar): Sales Performance */}
            <div className="xl:col-span-8">
                <div className="bg-white rounded-[2rem] p-8 shadow-sm border border-gray-100/50 h-[450px] flex flex-col hover:shadow-xl hover:shadow-indigo-50/50 transition-all duration-500">
                    <div className="flex items-center justify-between mb-8">
                        <div>
                            <h2 className="text-2xl font-bold text-gray-800">Sales Performance</h2>
                            <div className="flex items-center gap-2 text-sm text-gray-500 mt-1">
                                <Activity className="w-4 h-4 text-emerald-500" />
                                <span><span className="font-semibold text-gray-900">$128k</span> total revenue this month</span>
                            </div>
                        </div>

                        <div className="flex items-center gap-2 bg-gray-50 p-1 rounded-xl">
                            <button className="px-4 py-2 bg-white rounded-lg shadow-sm text-xs font-bold text-gray-800">Monthly</button>
                            <button className="px-4 py-2 hover:bg-white/50 rounded-lg text-xs font-medium text-gray-500 transition-colors">Weekly</button>
                        </div>
                    </div>

                    {/* Chart Real */}
                    <div className="flex-1 w-full bg-gradient-to-b from-transparent to-indigo-50/20 rounded-2xl border-2 border-dashed border-indigo-50 overflow-hidden relative">
                        <SalesChart subscriptionPlan={subscriptionPlan} />
                    </div>
                </div>
            </div>

            {/* Widget Bawah: Growth Mission */}
            <div className="xl:col-span-12">
                <div className="bg-white rounded-[2rem] p-8 shadow-sm border border-gray-100/50 hover:shadow-xl hover:shadow-indigo-50/50 transition-all duration-500">
                    <div className="flex items-center justify-between mb-8">
                        <div>
                            <h3 className="text-xl font-bold text-gray-800">Growth Missions</h3>
                            <p className="text-sm text-gray-500 mt-1">Complete these tasks to grow your business.</p>
                        </div>
                        <button className="text-sm text-indigo-600 font-bold hover:bg-indigo-50 px-4 py-2 rounded-xl transition-colors">View All Missions</button>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                        {[
                            { title: "Complete Store Profile", desc: "Add logo & description", progress: 85, color: "bg-indigo-500", icon: "🏪" },
                            { title: "Connect Marketplace", desc: "Link Tokopedia/Shopee", progress: 45, color: "bg-purple-500", icon: "🔗" },
                            { title: "First Ad Campaign", desc: "Reach 1000 customers", progress: 20, color: "bg-pink-500", icon: "📢" }
                        ].map((mission, i) => (
                            <div key={i} className="p-5 rounded-3xl bg-gray-50 border border-transparent hover:border-gray-200 hover:bg-white transition-all duration-300 group cursor-pointer">
                                <div className="flex justify-between items-start mb-4">
                                    <div className="w-10 h-10 bg-white rounded-xl shadow-sm flex items-center justify-center text-xl group-hover:scale-110 transition-transform">{mission.icon}</div>
                                    <span className="px-3 py-1 bg-white rounded-lg text-xs font-bold text-gray-900 shadow-sm">{mission.progress}%</span>
                                </div>

                                <h4 className="font-bold text-gray-800 mb-1">{mission.title}</h4>
                                <p className="text-xs text-gray-500 mb-4 font-medium">{mission.desc}</p>

                                <div className="h-2.5 w-full bg-gray-200/60 rounded-full overflow-hidden">
                                    <div className={`h-full ${mission.color} rounded-full transition-all duration-1000 ease-out`} style={{ width: `${mission.progress}%` }}></div>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            </div>

        </div>
    );
}
